apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: abeshith/myapp:80ec5f82a5503dafb9c07b5f85fe2e8eb6724b3a
        ports:
        - containerPort: 3000