name: Github Pipelines with ArgoCD

on:
  push:
    branches:
      - main

env:
    PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                fetch-depth: 0
            
            - name: Set up NodeJS
              uses: actions/setup-node@v2
              with:
                node-version: '14'

            - name: Install NodeJS dependencies
              run: npm install
                
            - name: Build Docker image
              run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/myapp:${{ github.sha }} .

            - name: Scan Docker image with Trivy
              run: |
                docker run --rm \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  aquasec/trivy:latest image ${{secrets.DOCKERHUB_USERNAME}}/myapp:${{ github.sha }} || true

            - name: Log in to Docker Hub Account
              run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            - name: Push Docker image to Docker Hub
              run:  docker push ${{secrets.DOCKERHUB_USERNAME}}/myapp:${{ github.sha }}